import { DetailedService } from "../types/index"; // Adjust the import path based on your project structure

const detailedServices: DetailedService[] = [
  {
    title: "Bridge Course & Entrance Preparation for +2",
    id: "bridge-course",
    details: [
      "Expert Guidance from Experienced Teachers to Ace Your +2 Entrance Exams",
      "Comprehensive Study Materials Covering All Subjects (Math, Science, English, and More)",
      "Regular Mock Tests with Detailed Feedback to Boost Your Confidence",
      "Personalized Support to Strengthen Weak Areas and Maximize Your Potential",
      "Interactive Group Study Sessions to Learn with Peers and Build Confidence",
      "Tips and Tricks to Manage Exam Stress and Perform Your Best",
      "Proven Strategies to Secure Admission in Top +2 Colleges in Nepal",
    ],
    image: "/entrance preparation.jpg",
    alt: "Student preparing for +2 entrance",
    bgColor: "bg-orange-50",
    textColor: "text-orange-600",
    buttonColor: "bg-orange-500 hover:bg-orange-600",
    checkColor: "text-orange-500",
    description:
      "Our Bridge Course & Entrance Preparation for +2 is designed to help students transition smoothly from SEE to higher secondary education in Nepal. This intensive program prepares students for entrance exams required by top +2 colleges, covering all major subjects and providing personalized support to ensure success.",
    duration: "6 Weeks",
    targetAudience: [
      "Students who have completed SEE and are preparing for +2 entrance exams",
      "Students aiming to join top +2 colleges in Nepal (e.g., St. Xavier’s, Budhanilkantha)",
      "Students seeking to build a strong academic foundation for Science, Management, or Humanities streams",
    ],
    prerequisites: [
      "Completion of SEE or equivalent examination",
      "Basic understanding of Class 10 subjects (Math, Science, English)",
    ],
    curriculum: {
      basic: [
        "Mathematics: Algebra, Geometry, Trigonometry, and Arithmetic",
        "Science: Physics (Mechanics, Heat, Light), Chemistry (Elements, Reactions), Biology (Human Body, Plants)",
        "English: Grammar, Comprehension, Essay Writing, Vocabulary",
        "General Knowledge: Current Affairs, Nepali History, Geography",
      ],
      advanced: [
        "Mathematics: Advanced Problem-Solving, Coordinate Geometry, Statistics",
        "Science: Practical Applications, Lab-Based Questions, Conceptual Analysis",
        "English: Critical Reading, Argumentative Writing, Interview Skills",
        "Entrance Exam Strategies: Time Management, Question Analysis, Mock Tests",
      ],
    },
    outcomes: [
      "Achieve high scores in +2 entrance exams",
      "Secure admission to top +2 colleges in Nepal",
      "Build a strong academic foundation for higher secondary education",
      "Develop confidence and exam-taking skills",
    ],
    certification: "Certificate of Completion for Bridge Course",
    price: "NPR 15,000",
    schedule: "Mon-Sat, 3 hours/day (Morning or Afternoon batches)",
  },
  {
    title: "3-Month Computer Training",
    id: "computer-training",
    details: [
      "Master the Office Package (MS Word, Excel, PowerPoint) to Excel in School Projects",
      "Multimedia & Internet Skills: Learn Photo Editing and Online Productivity Tools",
      "AI for Work: Use ChatGPT, Create AI-Powered Resumes, and Explore Freelancing Basics",
      "Create Professional Documents and Presentations for Academic Success",
      "Hands-On Projects to Build Digital Skills for the Future",
      "Get Certified and Add Valuable Skills to Your Resume",
      "Perfect for Post-SEE Students Starting Their Tech Journey!",
    ],
    image: "/computer class.jpg",
    alt: "computer class",
    bgColor: "bg-blue-50",
    textColor: "text-blue-700",
    buttonColor: "bg-blue-500 hover:bg-blue-600",
    checkColor: "text-yellow-500",
    description:
      "Our 3-Month Computer Training program is tailored for beginners and intermediate learners, focusing on essential digital skills for academic and professional success. From mastering Microsoft Office to exploring AI tools and multimedia, this course equips students with practical skills for the modern world.",
    duration: "3 Months (Optional 6-Month Extended Program Available)",
    targetAudience: [
      "Post-SEE students looking to gain digital skills",
      "Beginners with little to no computer experience",
      "Students preparing for higher education or part-time jobs requiring computer literacy",
    ],
    prerequisites: [
      "Basic understanding of computers (e.g., how to use a keyboard and mouse)",
      "No prior technical knowledge required",
    ],
    curriculum: {
      basic: [
        "Introduction to Computers: Hardware, Software, Operating Systems (Windows)",
        "Microsoft Word: Document Creation, Formatting, Tables, Templates",
        "Microsoft Excel: Spreadsheets, Formulas, Charts, Data Sorting",
        "Microsoft PowerPoint: Presentation Design, Slides, Animations",
        "Internet Basics: Browsing, Email, Online Safety",
      ],
      advanced: [
        "Multimedia Skills: Photo Editing with Canva, Basic Video Editing",
        "AI Tools: Using ChatGPT for Productivity, AI-Powered Resume Building",
        "Freelancing Basics: Introduction to Upwork, Fiverr, and Online Job Platforms",
        "Advanced Excel: Pivot Tables, VLOOKUP, Macros",
        "Cloud Tools: Google Drive, Docs, Sheets, and Collaboration",
      ],
      other: [
        "Hands-On Projects: Create a Resume, Design a Presentation, Build a Digital Portfolio",
        "Typing Skills: Improve Speed and Accuracy with Typing Software",
        "Cybersecurity Basics: Password Management, Avoiding Scams",
      ],
    },
    outcomes: [
      "Master essential computer skills for academic and professional use",
      "Create professional documents, presentations, and spreadsheets",
      "Gain confidence in using AI tools and multimedia software",
      "Earn a certificate to enhance your resume",
      "Prepare for part-time jobs or freelancing opportunities",
    ],
    certification: "Certificate in Computer Literacy",
    price: "NPR 10,000 (3 Months) / NPR 18,000 (6 Months)",
    schedule: "Mon-Fri, 2 hours/day (Morning or Evening batches)",
  },
  {
    title: "Coaching for Classes 6-10",
    id: "coaching",
    details: [
      "Interactive Classes with Fun Activities for Better Understanding",
      "Focus on Core Subjects (Math, Science, English, Social Studies, and Nepali)",
      "Regular Assessments with Progress Reports to Track Your Growth",
      "Learn from Experienced Teachers Specializing in Classes 5-10 Curriculum",
      "Small Batch Sizes for Personalized Attention and Doubt Clearing",
      "Exam Preparation Tips to Score High in SEE and School Exams",
      "Build a Strong Foundation for Your Academic Future in Nepal!",
    ],
    image: "/coachingclass.jpg",
    alt: "coaching class",
    bgColor: "bg-white",
    textColor: "text-blue-700",
    buttonColor: "bg-blue-500 hover:bg-blue-600",
    checkColor: "text-yellow-500",
    description:
      "Our Coaching for Classes 6-10 provides comprehensive academic support for students in Nepal, focusing on core subjects and exam preparation. With interactive teaching methods, small batch sizes, and regular assessments, we help students build a strong foundation for SEE and beyond.",
    duration: "Ongoing (Monthly Enrollment)",
    targetAudience: [
      "Students in Classes 6 to 10",
      "Students preparing for SEE (Class 10)",
      "Students needing extra support in core subjects",
    ],
    prerequisites: [
      "Enrollment in Classes 6 to 10",
      "Basic understanding of the respective class curriculum",
    ],
    curriculum: {
      basic: [
        "Mathematics: Arithmetic, Algebra, Geometry, Number Systems",
        "Science: Physics (Motion, Energy), Chemistry (Elements, Reactions), Biology (Cells, Plants)",
        "English: Grammar, Comprehension, Writing Skills, Vocabulary",
        "Social Studies: Nepali History, Geography, Civics",
        "Nepali: Grammar, Literature, Essay Writing",
      ],
      advanced: [
        "Mathematics: Trigonometry, Statistics, Advanced Algebra",
        "Science: Practical Applications, Lab-Based Questions, Conceptual Analysis",
        "English: Critical Reading, Creative Writing, Public Speaking",
        "Social Studies: Current Affairs, Global Issues, Map Skills",
        "SEE Preparation: Mock Tests, Time Management, Question Analysis",
      ],
    },
    outcomes: [
      "Improve grades in school exams",
      "Score high in SEE (Class 10) exams",
      "Develop strong study habits and academic skills",
      "Gain confidence in core subjects",
      "Prepare for higher secondary education",
    ],
    certification: "Progress Report and Certificate of Participation",
    price: "NPR 5,000/month",
    schedule: "Mon-Sat, 1.5 hours/day (After school hours)",
  },
  {
    title: "Mobile Repairing",
    id: "mobile-repairing",
    details: [
      "Hands-On Training with Real Smartphones to Master Repair Skills",
      "Learn to Diagnose and Fix Common Issues (Screen, Battery, Software Problems)",
      "Understand Both Hardware and Software Repairs for All Devices",
      "Guidance from Industry Experts with Years of Experience",
      "Start Earning Early: Learn Skills for Part-Time Jobs or Entrepreneurship",
      "Get Certified and Build a Career in Mobile Repairing Across Nepal",
      "Practical Workshops to Boost Confidence and Problem-Solving Skills",
    ],
    image: "/mobile repairing.jpg",
    alt: "mobile repairing",
    bgColor: "bg-blue-50",
    textColor: "text-blue-700",
    buttonColor: "bg-blue-500 hover:bg-blue-600",
    checkColor: "text-yellow-500",
    description:
      "Our Mobile Repairing course offers hands-on training to master the art of diagnosing and fixing smartphone issues. From hardware repairs to software troubleshooting, this course prepares students for a lucrative career in mobile repairing, with practical workshops and industry insights.",
    duration: "3 Months",
    targetAudience: [
      "Individuals interested in a career in mobile repairing",
      "Post-SEE students looking for vocational skills",
      "Entrepreneurs wanting to start a mobile repair business",
    ],
    prerequisites: [
      "Basic understanding of smartphones",
      "No prior technical experience required",
    ],
    curriculum: {
      basic: [
        "Introduction to Smartphones: Components, Tools, Safety Precautions",
        "Hardware Basics: Screen Replacement, Battery Replacement, Charging Port Repair",
        "Software Basics: Flashing, Unlocking, Factory Reset",
        "Diagnostics: Identifying Common Issues (e.g., No Power, No Display)",
      ],
      advanced: [
        "Advanced Hardware Repairs: Motherboard Repair, IC Replacement",
        "Software Troubleshooting: Fixing Boot Loops, Software Crashes",
        "Specialized Repairs: Water Damage Recovery, Camera Repair",
        "Business Skills: Sourcing Parts, Customer Service, Pricing Strategies",
      ],
      other: [
        "Practical Workshops: Hands-On Repair Sessions with Real Devices",
        "Industry Insights: Trends in Mobile Technology, Market Demand",
      ],
    },
    outcomes: [
      "Master mobile repairing skills for hardware and software",
      "Start a career in mobile repairing or open your own repair shop",
      "Earn a certificate to validate your skills",
      "Gain confidence in diagnosing and fixing smartphone issues",
    ],
    certification: "Certificate in Mobile Repairing",
    price: "NPR 20,000",
    schedule: "Mon-Fri, 3 hours/day (Morning or Afternoon batches)",
  },
  {
    title: "Programming Languages",
    id: "programming",
    details: [
      "Learn Popular Languages (Python, JavaScript, C++) with Step-by-Step Guidance",
      "Build Exciting Projects Like Games, Websites, and Apps to Showcase Your Skills",
      "Understand Algorithms and Data Structures to Solve Real-World Problems",
      "Prepare for a High-Demand Career in Coding and Software Development",
      "Participate in Coding Challenges and Competitions to Test Your Skills",
      "Get Mentorship from Expert Programmers to Guide Your Journey",
      "Start Your Coding Journey Today and Shape Your Future in Tech!",
    ],
    image: "/coding class.jpg",
    alt: "coding class",
    bgColor: "bg-white",
    textColor: "text-blue-700",
    buttonColor: "bg-blue-500 hover:bg-blue-600",
    checkColor: "text-yellow-500",
    description:
      "Our Programming Languages course is designed for beginners and intermediate learners, covering a wide range of languages including HTML, CSS, JavaScript, Python, C, C++, and Java. With a focus on both basic and advanced topics, this course prepares students for a career in software development through hands-on projects and expert mentorship.",
    duration: "6 Months",
    targetAudience: [
      "Beginners with no prior coding experience",
      "Post-SEE students interested in a tech career",
      "Intermediate learners looking to deepen their programming skills",
    ],
    prerequisites: [
      "Basic computer literacy",
      "No prior programming experience required",
    ],
    curriculum: {
      basic: [
        "HTML: Structure of Web Pages, Tags, Attributes, Forms",
        "CSS: Styling, Selectors, Box Model, Flexbox, Grid",
        "JavaScript: Variables, Functions, DOM Manipulation, Events",
        "Python: Syntax, Variables, Loops, Functions, Lists",
        "C: Syntax, Variables, Loops, Functions, Pointers",
        "C++: Syntax, OOP Concepts (Classes, Objects), Arrays",
        "Java: Syntax, Variables, Loops, Methods, Classes",
      ],
      advanced: [
        "HTML: Semantic HTML, Accessibility, SEO Basics",
        "CSS: Animations, Transitions, Responsive Design, CSS Variables",
        "JavaScript: ES6+, Async/Await, APIs, Closures, Modules",
        "Python: Object-Oriented Programming, File Handling, Libraries (NumPy, Pandas)",
        "C: Memory Management, Data Structures (Linked Lists, Stacks)",
        "C++: Templates, STL (Standard Template Library), Exception Handling",
        "Java: Collections, Multithreading, JDBC, Spring Framework Basics",
        "Algorithms: Sorting, Searching, Recursion, Time Complexity",
        "Data Structures: Arrays, Linked Lists, Stacks, Queues, Trees, Graphs",
      ],
      other: [
        "Projects: Build a Website, Create a Calculator, Develop a Simple Game",
        "Coding Challenges: Participate in Hackathons and Competitions",
        "Version Control: Introduction to Git and GitHub",
      ],
    },
    outcomes: [
      "Master multiple programming languages and their applications",
      "Build a portfolio of projects to showcase your skills",
      "Understand algorithms and data structures for problem-solving",
      "Prepare for a career in software development",
      "Gain confidence in coding and project development",
    ],
    certification: "Certificate in Programming Languages",
    price: "NPR 25,000",
    schedule: "Mon-Fri, 2 hours/day (Evening batches)",
  },
  {
    title: "Full Stack Web Development",
    id: "web-development",
    details: [
      "Master Frontend & Backend Development with HTML, CSS, JavaScript, and More",
      "Build Real-World, Scalable Projects Like E-Commerce Sites and Blogs",
      "Work with Git & GitHub to Collaborate on Projects Like a Pro",
      "Create and Manage APIs & Databases for Dynamic Web Applications",
      "Deploy Your Projects Online and Build a Portfolio to Impress Employers",
      "Get Job-Ready with Skills in High Demand Across Nepal and Globally",
      "Learn from Industry Experts and Start Your Career in Web Development!",
    ],
    image: "/webdevelopment.jpg",
    alt: "web development",
    bgColor: "bg-blue-50",
    textColor: "text-blue-700",
    buttonColor: "bg-blue-500 hover:bg-blue-600",
    checkColor: "text-yellow-500",
    description:
      "Our Full Stack Web Development course takes you from beginner to job-ready developer, covering both frontend and backend technologies. Learn to build dynamic, scalable web applications using modern tools and frameworks, and deploy your projects online to build a professional portfolio.",
    duration: "6 Months",
    targetAudience: [
      "Beginners interested in a career in web development",
      "Intermediate developers looking to become full stack developers",
      "Professionals seeking to upskill for better job opportunities",
    ],
    prerequisites: [
      "Basic understanding of HTML, CSS, and JavaScript",
      "Familiarity with programming concepts",
    ],
    curriculum: {
      basic: [
        "HTML: Semantic HTML, Forms, Accessibility",
        "CSS: Flexbox, Grid, Responsive Design, Tailwind CSS",
        "JavaScript: ES6+, DOM Manipulation, Events, Fetch API",
        "Version Control: Git, GitHub, Branching, Pull Requests",
        "Frontend Tools: VS Code, Browser DevTools",
      ],
      advanced: [
        "Frontend Frameworks: React (Components, Hooks, State Management)",
        "Backend Development: Node.js, Express.js, REST APIs",
        "Databases: MongoDB (CRUD Operations), SQL Basics (MySQL)",
        "Authentication: JWT, OAuth, User Login Systems",
        "Deployment: Vercel, Netlify, Heroku, Domain Management",
        "Testing: Unit Testing with Jest, Debugging",
      ],
      other: [
        "Projects: Build an E-Commerce Site, Create a Blog, Develop a Task Manager",
        "APIs: Integrate Third-Party APIs (e.g., Payment Gateways, Google Maps)",
        "Best Practices: Code Reviews, Performance Optimization, SEO",
      ],
    },
    outcomes: [
      "Build and deploy full stack web applications",
      "Create a professional portfolio with real-world projects",
      "Master frontend and backend development skills",
      "Prepare for job roles like Full Stack Developer, Web Developer",
      "Gain confidence in working with modern web technologies",
    ],
    certification: "Certificate in Full Stack Web Development",
    price: "NPR 35,000",
    schedule: "Mon-Fri, 3 hours/day (Morning or Evening batches)",
  },
];

export { detailedServices };